# Generated by Django 4.2.7 on 2025-10-06 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("title", "task_list")},
        ),
        migrations.AlterUniqueTogether(
            name="tasklist",
            unique_together={("name", "created_by")},
        ),
    ]
